# action.yml
name: "Gemini Review Bot"
description: "Review Pull Requests using Gemini"
author: "Your Name or Org"

inputs:
  GEMINI_API_KEY:
    description: "Gemini API Key"
    required: true
    default: ""
  GITHUB_TOKEN:
    description: "GitHub Token"
    required: false

runs:
  using: "composite"
  steps:
    - name: Check out action repository
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Run review bot
      run: node dist/index.js
      shell: bash
      env:
        GEMINI_API_KEY: ${{ inputs.GEMINI_API_KEY }}
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GITHUB_OWNER: ${{ github.repository_owner }}
        GITHUB_REPO: ${{ github.event.pull_request.head.repo.name }}
        GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
